name: 🔄 Vercel Rollback

on:
  workflow_dispatch:
    inputs:
      deployment_url:
        description: 'Specific deployment URL to rollback to (leave empty for automatic rollback to previous deployment)'
        required: false
        type: string
      reason:
        description: 'Reason for rollback (for logging)'
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest
    name: 🔄 Rollback Deployment
    
    steps:
      - name: 🚀 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: 📦 Install Vercel CLI
        run: npm install -g vercel@latest
        
      - name: 🔄 Execute Rollback
        run: |
          echo "🚨 ROLLBACK INITIATED"
          echo "📝 Reason: ${{ github.event.inputs.reason }}"
          echo "👤 Initiated by: ${{ github.actor }}"
          echo "⏰ Time: $(date)"
          echo ""
          
          if [ -n "${{ github.event.inputs.deployment_url }}" ]; then
            echo "🎯 Rolling back to specific deployment: ${{ github.event.inputs.deployment_url }}"
            vercel rollback "${{ github.event.inputs.deployment_url }}" --token ${{ secrets.VERCEL_TOKEN }} --yes
          else
            echo "⏮️ Rolling back to previous deployment automatically"
            vercel rollback --token ${{ secrets.VERCEL_TOKEN }} --yes
          fi
          
      - name: ✅ Verify Rollback
        run: |
          echo "✅ Rollback completed successfully!"
          echo "🔍 Current production status:"
          vercel ls --token ${{ secrets.VERCEL_TOKEN }} --yes | head -3
          echo ""
          echo "🎉 Production has been rolled back!"
          echo "📊 Check your site to verify the rollback was successful." 