name: 🔍 Test Supabase Connection

on:
  workflow_dispatch:

jobs:
  test-connection:
    name: 🔍 Test Database Connection
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4
    
    - name: 🛠️ Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client netcat-traditional
    
    - name: 🗄️ Setup Environment
      run: |
        echo "SUPABASE_PROJECT_REF=${{ secrets.SUPABASE_PROJECT_REF }}" >> $GITHUB_ENV
        echo "SUPABASE_DB_PASSWORD=${{ secrets.SUPABASE_DB_PASSWORD }}" >> $GITHUB_ENV
        echo "SUPABASE_POOLER_HOST=${{ secrets.SUPABASE_POOLER_HOST }}" >> $GITHUB_ENV
        echo "SUPABASE_POOLER_PORT=${{ secrets.SUPABASE_POOLER_PORT }}" >> $GITHUB_ENV
    
    - name: 🔍 Test Connection
      run: |
        chmod +x scripts/ops/test-connection.sh
        ./scripts/ops/test-connection.sh 