name: 🎯 Direct Backup Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of backup test to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - schema-only
          - data-only

jobs:
  test-direct-backup:
    name: Test direct backup functionality
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          
      - name: Test direct backup functionality
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          SUPABASE_POOLER_HOST: ${{ secrets.SUPABASE_POOLER_HOST }}
          SUPABASE_POOLER_PORT: ${{ secrets.SUPABASE_POOLER_PORT }}
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
        run: |
          echo "🎯 Running direct backup test"
          echo "Test type: ${{ github.event.inputs.test_type || 'all' }}"
          
          # Run the direct backup test
          ./scripts/ops/test-backup-direct.sh
          
      - name: Upload backup test files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-test-files
          path: test-backups/
          retention-days: 7 